<a href="https://www.kaggle.com/code/hetvipatel22/linear-regression?scriptVersionId=155874895" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/metro-interstate-traffic-volume/Metro_Interstate_Traffic_Volume.csv


In [2]:
import pandas as pd
##https://archive.ics.uci.edu/ml/datasets/Metro+Interstate+Traffic+Volume
path = "/kaggle/input/metro-interstate-traffic-volume/Metro_Interstate_Traffic_Volume.csv"
df = pd.read_csv(path) #na_values are used to use NaN inplace of ?? in dataset. Nan is standard name for missing value
print("The first 5 rows of the dataframe") 
df.head(10)

The first 5 rows of the dataframe


holiday    temp  rain_1h  snow_1h  clouds_all weather_main  \
0     NaN  288.28      0.0      0.0          40       Clouds   
1     NaN  289.36      0.0      0.0          75       Clouds   
2     NaN  289.58      0.0      0.0          90       Clouds   
3     NaN  290.13      0.0      0.0          90       Clouds   
4     NaN  291.14      0.0      0.0          75       Clouds   
5     NaN  291.72      0.0      0.0           1        Clear   
6     NaN  293.17      0.0      0.0           1        Clear   
7     NaN  293.86      0.0      0.0           1        Clear   
8     NaN  294.14      0.0      0.0          20       Clouds   
9     NaN  293.10      0.0      0.0          20       Clouds   

  weather_description            date_time  traffic_volume  
0    scattered clouds  2012-10-02 09:00:00            5545  
1       broken clouds  2012-10-02 10:00:00            4516  
2     overcast clouds  2012-10-02 11:00:00            4767  
3     overcast clouds  2012-10-02 12:00:00            5026  
4       broken clouds  2012-10-02 13:00:00            4918  
5        sky is clear  2012-10-02 14:00:00            5181  
6        sky is clear  2012-10-02 15:00:00            5584  
7        sky is clear  2012-10-02 16:00:00            6015  
8          few clouds  2012-10-02 17:00:00            5791  
9          few clouds  2012-10-02 18:00:00            4770

In [3]:
import numpy as np
df=df.replace("?",np.nan)
df.head(10)

holiday    temp  rain_1h  snow_1h  clouds_all weather_main  \
0     NaN  288.28      0.0      0.0          40       Clouds   
1     NaN  289.36      0.0      0.0          75       Clouds   
2     NaN  289.58      0.0      0.0          90       Clouds   
3     NaN  290.13      0.0      0.0          90       Clouds   
4     NaN  291.14      0.0      0.0          75       Clouds   
5     NaN  291.72      0.0      0.0           1        Clear   
6     NaN  293.17      0.0      0.0           1        Clear   
7     NaN  293.86      0.0      0.0           1        Clear   
8     NaN  294.14      0.0      0.0          20       Clouds   
9     NaN  293.10      0.0      0.0          20       Clouds   

  weather_description            date_time  traffic_volume  
0    scattered clouds  2012-10-02 09:00:00            5545  
1       broken clouds  2012-10-02 10:00:00            4516  
2     overcast clouds  2012-10-02 11:00:00            4767  
3     overcast clouds  2012-10-02 12:00:00            5026  
4       broken clouds  2012-10-02 13:00:00            4918  
5        sky is clear  2012-10-02 14:00:00            5181  
6        sky is clear  2012-10-02 15:00:00            5584  
7        sky is clear  2012-10-02 16:00:00            6015  
8          few clouds  2012-10-02 17:00:00            5791  
9          few clouds  2012-10-02 18:00:00            4770

In [4]:
df.isnull().sum()

holiday                48143
temp                       0
rain_1h                    0
snow_1h                    0
clouds_all                 0
weather_main               0
weather_description        0
date_time                  0
traffic_volume             0
dtype: int64

In [5]:
df.dtypes

holiday                 object
temp                   float64
rain_1h                float64
snow_1h                float64
clouds_all               int64
weather_main            object
weather_description     object
date_time               object
traffic_volume           int64
dtype: object

In [6]:
df.tail(10)

holiday    temp  rain_1h  snow_1h  clouds_all  weather_main  \
48194     NaN  283.84     0.00      0.0          75          Rain   
48195     NaN  283.84     0.00      0.0          75       Drizzle   
48196     NaN  284.38     0.00      0.0          75          Rain   
48197     NaN  284.79     0.00      0.0          75        Clouds   
48198     NaN  284.20     0.25      0.0          75          Rain   
48199     NaN  283.45     0.00      0.0          75        Clouds   
48200     NaN  282.76     0.00      0.0          90        Clouds   
48201     NaN  282.73     0.00      0.0          90  Thunderstorm   
48202     NaN  282.09     0.00      0.0          90        Clouds   
48203     NaN  282.12     0.00      0.0          90        Clouds   

           weather_description            date_time  traffic_volume  
48194    proximity shower rain  2018-09-30 15:00:00            4302  
48195  light intensity drizzle  2018-09-30 15:00:00            4302  
48196               light rain  2018-09-30 16:00:00            4283  
48197            broken clouds  2018-09-30 17:00:00            4132  
48198               light rain  2018-09-30 18:00:00            3947  
48199            broken clouds  2018-09-30 19:00:00            3543  
48200          overcast clouds  2018-09-30 20:00:00            2781  
48201   proximity thunderstorm  2018-09-30 21:00:00            2159  
48202          overcast clouds  2018-09-30 22:00:00            1450  
48203          overcast clouds  2018-09-30 23:00:00             954

In [7]:
df.dtypes

holiday                 object
temp                   float64
rain_1h                float64
snow_1h                float64
clouds_all               int64
weather_main            object
weather_description     object
date_time               object
traffic_volume           int64
dtype: object

In [8]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder

# Creating a instance of label Encoder.
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['weather_main'])

# printing label
label


array([ 1,  1,  1, ..., 10,  1,  1])

In [9]:
# removing the column 'Weather_main' from df as it is of no use now.
df.drop("weather_main", axis=1, inplace=True)
df["weather_main"] = label
df


holiday    temp  rain_1h  snow_1h  clouds_all     weather_description  \
0         NaN  288.28      0.0      0.0          40        scattered clouds   
1         NaN  289.36      0.0      0.0          75           broken clouds   
2         NaN  289.58      0.0      0.0          90         overcast clouds   
3         NaN  290.13      0.0      0.0          90         overcast clouds   
4         NaN  291.14      0.0      0.0          75           broken clouds   
...       ...     ...      ...      ...         ...                     ...   
48199     NaN  283.45      0.0      0.0          75           broken clouds   
48200     NaN  282.76      0.0      0.0          90         overcast clouds   
48201     NaN  282.73      0.0      0.0          90  proximity thunderstorm   
48202     NaN  282.09      0.0      0.0          90         overcast clouds   
48203     NaN  282.12      0.0      0.0          90         overcast clouds   

                 date_time  traffic_volume  weather_main  
0      2012-10-02 09:00:00            5545             1  
1      2012-10-02 10:00:00            4516             1  
2      2012-10-02 11:00:00            4767             1  
3      2012-10-02 12:00:00            5026             1  
4      2012-10-02 13:00:00            4918             1  
...                    ...             ...           ...  
48199  2018-09-30 19:00:00            3543             1  
48200  2018-09-30 20:00:00            2781             1  
48201  2018-09-30 21:00:00            2159            10  
48202  2018-09-30 22:00:00            1450             1  
48203  2018-09-30 23:00:00             954             1  

[48204 rows x 9 columns]

In [10]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder

# Creating a instance of label Encoder.
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['holiday'])

# printing label
label


array([11, 11, 11, ..., 11, 11, 11])

In [11]:

df.drop("holiday", axis=1, inplace=True)
df["holiday"] = label
df


temp  rain_1h  snow_1h  clouds_all     weather_description  \
0      288.28      0.0      0.0          40        scattered clouds   
1      289.36      0.0      0.0          75           broken clouds   
2      289.58      0.0      0.0          90         overcast clouds   
3      290.13      0.0      0.0          90         overcast clouds   
4      291.14      0.0      0.0          75           broken clouds   
...       ...      ...      ...         ...                     ...   
48199  283.45      0.0      0.0          75           broken clouds   
48200  282.76      0.0      0.0          90         overcast clouds   
48201  282.73      0.0      0.0          90  proximity thunderstorm   
48202  282.09      0.0      0.0          90         overcast clouds   
48203  282.12      0.0      0.0          90         overcast clouds   

                 date_time  traffic_volume  weather_main  holiday  
0      2012-10-02 09:00:00            5545             1       11  
1      2012-10-02 10:00:00            4516             1       11  
2      2012-10-02 11:00:00            4767             1       11  
3      2012-10-02 12:00:00            5026             1       11  
4      2012-10-02 13:00:00            4918             1       11  
...                    ...             ...           ...      ...  
48199  2018-09-30 19:00:00            3543             1       11  
48200  2018-09-30 20:00:00            2781             1       11  
48201  2018-09-30 21:00:00            2159            10       11  
48202  2018-09-30 22:00:00            1450             1       11  
48203  2018-09-30 23:00:00             954             1       11  

[48204 rows x 9 columns]

In [12]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['weather_description'])
label


array([24,  2, 19, ..., 21, 19, 19])

In [13]:
df.drop("weather_description", axis=1, inplace=True)
df["weather_description"] = label
df

temp  rain_1h  snow_1h  clouds_all            date_time  \
0      288.28      0.0      0.0          40  2012-10-02 09:00:00   
1      289.36      0.0      0.0          75  2012-10-02 10:00:00   
2      289.58      0.0      0.0          90  2012-10-02 11:00:00   
3      290.13      0.0      0.0          90  2012-10-02 12:00:00   
4      291.14      0.0      0.0          75  2012-10-02 13:00:00   
...       ...      ...      ...         ...                  ...   
48199  283.45      0.0      0.0          75  2018-09-30 19:00:00   
48200  282.76      0.0      0.0          90  2018-09-30 20:00:00   
48201  282.73      0.0      0.0          90  2018-09-30 21:00:00   
48202  282.09      0.0      0.0          90  2018-09-30 22:00:00   
48203  282.12      0.0      0.0          90  2018-09-30 23:00:00   

       traffic_volume  weather_main  holiday  weather_description  
0                5545             1       11                   24  
1                4516             1       11                    2  
2                4767             1       11                   19  
3                5026             1       11                   19  
4                4918             1       11                    2  
...               ...           ...      ...                  ...  
48199            3543             1       11                    2  
48200            2781             1       11                   19  
48201            2159            10       11                   21  
48202            1450             1       11                   19  
48203             954             1       11                   19  

[48204 rows x 9 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
#1.divide dataset in test data and train data
#divide x_data and y_data
y_data = df['traffic_volume']
x_data=df.drop('traffic_volume',axis=1)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=1)
#random_state=1 gives you different results everytime

print("number of test samples :", x_test.shape[0])
print("number of training samples:",x_train.shape[0])

number of test samples : 9641
number of training samples: 38563


In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [17]:
Z = x_train[['temp', 'clouds_all', 'weather_main', 'holiday','weather_description']]
y=y_train

In [18]:
from sklearn.linear_model import LinearRegression
lm1 = LinearRegression()
df.dtypes
lm1.fit(Z, y)
print(lm1.intercept_)
lm1.coef_

-5778.213221436636


array([ 20.8596622 ,   6.11389465, -74.39179093, 289.23906562,
        -7.06972164])

In [19]:
#predit values
#We can output a prediction
Y_predict_multifit=lm1.predict(Z) # this function is used to predict the price parameter x is array
print("predicted price for 0 to 4 index value is ",Y_predict_multifit[0:5])
print("actual values are",y[0:5])

predicted price for 0 to 4 index value is  [3663.05741515 3418.55670928 3520.57378595 3656.16159024 3446.1047919 ]
actual values are 16959    5445
6182     2337
42019     756
14034     355
5732     2299
Name: traffic_volume, dtype: int64


In [20]:
x1=x_test[['temp', 'clouds_all', 'weather_main', 'holiday','weather_description']]
y_1=y_test

#predit values
#We can output a prediction
Y_predict_multifit1=lm1.predict(x1) # this function is used to predict the price parameter x is array
print("predicted price for 0 to 4 index value is ",Y_predict_multifit1[0:5])
print("actual values are",y_1[0:5])

predicted price for 0 to 4 index value is  [3335.07764783 3057.68455324 3250.21923534 3596.40206738 3300.66473029]
actual values are 6715      812
27836    1241
43682    1703
41005    5829
28608    3798
Name: traffic_volume, dtype: int64


In [21]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
#We create the pipeline, by creating a list of tuples including the name of the model or estimator and its corresponding constructor.
Input=[('scale',StandardScaler()), ('polynomial', PolynomialFeatures(2)), ('model',LinearRegression())]
#we input the list as an argument to the pipeline constructo
pipe=Pipeline(Input)
pipe


Pipeline(steps=[('scale', StandardScaler()),
                ('polynomial', PolynomialFeatures()),
                ('model', LinearRegression())])

In [22]:
#We can normalize the data, perform a transform and fit the model simultaneously.
pipe.fit(Z,y)



Pipeline(steps=[('scale', StandardScaler()),
                ('polynomial', PolynomialFeatures()),
                ('model', LinearRegression())])

In [23]:
#We can normalize the data, perform a transform and fit the model simultaneously.
pipe.fit(x1,y_1)

ypipe=pipe.predict(Z)
ypipe[0:4]


array([4204.95527286, 3390.2405174 , 3332.43357083, 3539.00617602])

In [24]:
ypipe1=pipe.predict(x1)
ypipe1[0:4]

array([3287.11492294, 2927.70870137, 3167.57106633, 3573.05449281])

In [25]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
#multi linear regression
print("mutli linear regression model:")
print('R2: ', r2_score(y_1,  Y_predict_multifit1))
print('MSE: ', mean_squared_error(y_1, Y_predict_multifit1))


mutli linear regression model:
R2:  0.029981255827470243
MSE:  3807090.2776190806


In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("Mutli Poly regression model:")
print('R2: ', r2_score(y_1,  ypipe1))
print('MSE: ', mean_squared_error(y_1, ypipe1))


Mutli Poly regression model:
R2:  0.046456893724033166
MSE:  3742427.361329681
